/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TagId = bigint;
export interface Tag {
    id: TagId;
    name: string;
    color: string;
}
export interface GraphNode {
    id: DocumentId;
    title: string;
}
export interface GraphData {
    edges: Array<GraphEdge>;
    nodes: Array<GraphNode>;
}
export interface BacklinkRef {
    id: DocumentId;
    title: string;
}
export interface DocumentVersion {
    title: string;
    content: string;
    savedAt: bigint;
}
export interface GraphEdge {
    source: DocumentId;
    target: DocumentId;
}
export type DocumentId = bigint;
export interface Document {
    id: DocumentId;
    title: string;
    content: string;
    createdAt: bigint;
    tagIds: Array<TagId>;
    updatedAt: bigint;
}
export interface UserProfile {
    name: string;
}
export interface backendInterface {
    createDocument(title: string): Promise<Document>;
    createTag(name: string, color: string): Promise<Tag>;
    deleteDocument(id: DocumentId): Promise<void>;
    deleteTag(id: TagId): Promise<void>;
    getAllTags(): Promise<Array<Tag>>;
    getBacklinks(id: DocumentId): Promise<Array<BacklinkRef>>;
    getDocument(id: DocumentId): Promise<Document | null>;
    getDocumentByTitle(title: string): Promise<Document | null>;
    getDocuments(searchQuery: string, filterTagIds: Array<TagId>, sortBy: string): Promise<Array<Document>>;
    getGraphData(): Promise<GraphData>;
    getProfile(): Promise<UserProfile | null>;
    getVersions(id: DocumentId): Promise<Array<DocumentVersion>>;
    restoreVersion(id: DocumentId, versionIndex: bigint): Promise<Document>;
    saveVersion(id: DocumentId): Promise<void>;
    setProfile(name: string): Promise<void>;
    updateDocument(id: DocumentId, title: string, content: string, tagIds: Array<TagId>): Promise<Document>;
    updateTag(id: TagId, name: string, color: string): Promise<Tag>;
}
import type { Document as _Document, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createDocument(arg0: string): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0);
            return result;
        }
    }
    async createTag(arg0: string, arg1: string): Promise<Tag> {
        if (this.processError) {
            try {
                const result = await this.actor.createTag(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTag(arg0, arg1);
            return result;
        }
    }
    async deleteDocument(arg0: DocumentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteTag(arg0: TagId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTag(arg0);
            return result;
        }
    }
    async getAllTags(): Promise<Array<Tag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTags();
            return result;
        }
    }
    async getBacklinks(arg0: DocumentId): Promise<Array<BacklinkRef>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBacklinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBacklinks(arg0);
            return result;
        }
    }
    async getDocument(arg0: DocumentId): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentByTitle(arg0: string): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentByTitle(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentByTitle(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocuments(arg0: string, arg1: Array<TagId>, arg2: string): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocuments(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocuments(arg0, arg1, arg2);
            return result;
        }
    }
    async getGraphData(): Promise<GraphData> {
        if (this.processError) {
            try {
                const result = await this.actor.getGraphData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGraphData();
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVersions(arg0: DocumentId): Promise<Array<DocumentVersion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVersions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVersions(arg0);
            return result;
        }
    }
    async restoreVersion(arg0: DocumentId, arg1: bigint): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreVersion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreVersion(arg0, arg1);
            return result;
        }
    }
    async saveVersion(arg0: DocumentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVersion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVersion(arg0);
            return result;
        }
    }
    async setProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0);
            return result;
        }
    }
    async updateDocument(arg0: DocumentId, arg1: string, arg2: string, arg3: Array<TagId>): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTag(arg0: TagId, arg1: string, arg2: string): Promise<Tag> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTag(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTag(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
